config/routes.rb
Rails.application.routes.draw do
  # get 'bookshelves/new'
  # get 'bookmarks/new'
  # post 'bookmarks/new'
  # post 'bookmarks/save', to:  'bookmarks#save'
  # get  'bookshelf/new'
  post 'bookshelves/save', to:  'bookshelves#save'
  # get 'urls/new'
  # get 'urls/show'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :bookmarks
  resources :urls
  resources :bookshelves
  resources :links
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  # validates :url, presence: true
  validates :title, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :books
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :user_id, presence: true
  # validates :description, presence: true
  # validates :title, presence: true
  # validates :image, presence: true

  belongs_to :user
  has_many :urls, dependent: :destroy
  accepts_nested_attributes_for :urls,  allow_destroy: true
  has_many :bookshelves
end

app/models/bookshelf.rb
class Bookshelf < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_many :bookmarks
  acts_as_paranoid
  # accepts_nested_attributes_for :urls,  allow_destroy: true

end

app/models/url.rb
class Url < ApplicationRecord
  validates :url, presence: true
  # belongs_to :user
  belongs_to :bookmark
  has_many :bookshelves
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
  # パスワードの文字数を8~32文字のみ可能にしてください
  validates :password,
            length: { minimum: 8, maximum: 32 }
  # アルファベットだけ、数字だけのパスワードは不可とします。
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/i }

  # 最低限「~ @ ~ . ~」の形を許可するようにしてください。
  validates :email,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # 15文字まで許可するようにバリデーションを設定してください。
  validates :name,
            length: { maximum: 15 }

  has_many :bookmarks
  has_many :urls
  has_many :bookshelves
  accepts_nested_attributes_for :urls, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :logged_in_user, only: [:post, :index, :edit, :update, :destroy]
  def index
    # ログインしているユーザーのみの情報を取得
    @bookmarks = current_user.bookmarks
  end

  def new
    @bookmark = Bookmark.new
    @bookmark.urls.build
  end

  def save
    @bookmark = Bookmark.new
    @bookmark.urls.build
    @bookmark = current_user.bookmarks.new(bookmark_params)
    @bookmark.save
  end

  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmarks_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update_attributes(bookmark_params)
      redirect_to bookmarks_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :edit
    end    
  end

  def destroy
    @bookmark = Bookmark.find_by(id: params[:id])
    @bookmark.destroy if @bookmark.present?
    redirect_to bookmarks_path, warning: 'Delete'
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:description, :title, urls_attributes: [:url, :_destroy,:id])
  end

end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
  before_action :logged_in_user, only: [:post, :index, :edit, :update, :destroy]
  def index
    # ログインしているユーザーのみの情報を取得
    @bookshelves = current_user.bookshelves
    @bookmarks = current_user.bookmarks
    @url = Url.new

  end

  # def show
  #   @bookmarks = Bookmark.find(params[:id])
  # end

  def new
    @bookshelf = Bookshelf.new
  end

  def save
      @bookshelf = Bookshelf.new(user_id: params[:user_id], url: params[:data])
      @bookshelf.save
  end

  def create
    @bookshelf = current_user.bookshelves.new(bookshelf_params)
    if @bookshelf.save
      redirect_to new_bookmark_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :new
    end
  end

  private
  def bookshelf_params
    params.require(:bookshelf).permit(:user_id, :url)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to bookmarks_path, success: 'Success'
      
    else
      flash.now[:danger] = 'Failure'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'Log out'
  end

  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
    @url.book_id = params[:bookmark_id]
    @url_user_id = session[:user_id]
  end

  def create
    @url = Url.new(url_params)
    if url_params[:bookmark_id].empty?
      flash[:danger] = "Please select bookmark."
      redirect_to bookshelves_path
    end
    if @url.save
      # bookshelf_params(ハッシュ)から:bookshelf_id(キー)を指定して、bookshelf_idのvalueを取り出す
      @bookshelf = Bookshelf.find(bookshelf_params[:bookshelf_id])
      @bookshelf.destroy if @bookshelf.present?
      redirect_to bookmarks_path, success: 'Add bookmark.'
    # else
    #   flash[:danger] = "ブックマークの追加に失敗しました"
    #   redirect_to bookshelves_path
    end
  end

  private
  def url_params
    params.require(:url).permit(:bookmark_id, :url)
  end

  def bookshelf_params
    params.require(:url).permit(:bookshelf_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end

  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/bookshelves_helper.rb
module BookshelvesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/edit.html.slim
.users-new-wrapper
  .container
    .row
      .col-offset-12.col-md-12.users-new-container
        h1.text-center.text-white
          | Edit
    = form_for @bookmark do |f|
      .container
        .row
          .col-md-8.ml-auto
            div class="form-group"
              = f.text_field :title, class: 'title-form form', placeholder: "TITLE"
              = f.text_area :description, class: 'description-form form', placeholder: "DESCRIPTION"
              / = f.text_area :url, class: 'form-control'
                  / = f.fields_for :urls do |u|
              = f.nested_fields_for :urls do |uu|
                / URLの入力項目を動的に追加・削除
                = uu.remove_nested_fields_link 'DELETE', class: 'btn btn-danger', role: 'button'
                = uu.text_field :url, class: 'title-form form', placeholder: "URL"
                / = uu.check_box :_destroy
                / = uu.label :_destroy, "削除"
              = f.add_nested_fields_link :urls, 'ADD', class: 'btn btn-primary', role: 'button'
            - if logged_in?
              = f.submit 'Update', class: 'btn btn-white form-btn btn-size'

app/views/bookmarks/index.html.slim
.bookmark-index-wrapper
  .col-md-12
    h1.text-center.text-white
      | Bookmark
    .container
      .row
        .col-md-6.position-fixed.offset-md-5#z-1000
          .iframe-wrap
            | 　
            iframe#link height="100px" src="" width="100%"
        .col-md-6#mt-50
          - @bookmarks.each do |bookmark|
            .col-md-12.mb-5
              .bookmark-index-single
                h5.bookmark-author
                  = bookmark.user.name 
                  =link_to '', edit_bookmark_path(bookmark.id), class: "fas fa-cog icons edit"
                  =link_to '', bookmark_path(id: bookmark.id), method: :delete, class: "fas fa-trash-alt icons delete"
                h3.bookmark-text
                  = bookmark.title
                p.bookmark-text
                  = bookmark.description 
                - bookmark.urls.each do |url|
                  p.bookmark-text
                    / "#link"の"src"タグの中に入れてプレビューを表示
                    = link_to(url.url, 'javascript:void(0);', onclick: "setName('#{url.url}');return false;")
                    / = raw Rinku.auto_link(url.url, :all, 'target="_blank"')
                    / ボタンを押すと、"button"に格納されたURLをJavascriptが取得、
                    / 登録したURLが自動的に外部リンクとなる
                    button.fas.fa-external-link-alt onclick="window.open('#{url.url}')"
      
javascript:
   function setName( $src ) {
   var $elementReference = document.getElementById( "link" );
   $elementReference.src = $src;
   var $elementmt50 = document.getElementById( "mt-50" );
   var $elementz1000 = document.getElementById( "z-1000" );
   $elementmt50.classList.add("mt-50");
   $elementz1000.classList.add("z-1000");
   }
/ javascript:
/   const box = 'iframe#link height="100px" src="" width="100%"'
/   document.getElementById("button").onclick = function() {
/     window.insertAdjacentHTML('afterend', box);
/    }
/ script
/   | $(function(){
/   | if(window.matchMedia("(max-width:500px)").matches){
/   | $('.up').addClass('order-2');
/   | $('.under').addClass('order-1');
/   | }else{
/   | $('.up').removeClass('order-2');
/   | $('.under').removeClass('order-1');
/   | }
/   | })
                  

app/views/bookmarks/new.html.slim
.users-new-wrapper
  .container
    .row
      .col-offset-12.col-md-12.users-new-container
        h1.text-center.text-white
          | Save URL
    = form_for @bookmark do |f|
      .container
        .row
          .col-md-8.ml-auto
            div class="form-group"
              = f.text_field :title, class: 'title-form form', placeholder: "TITLE"
              = f.text_area :description, class: 'description-form form', placeholder: "DESCRIPTION"
              / = f.text_area :url, class: 'form-control'
                  / = f.fields_for :urls do |u|
              = f.nested_fields_for :urls do |uu|
                / URLの入力項目を動的に追加・削除
                = uu.remove_nested_fields_link 'DELETE', class: 'btn btn-danger', role: 'button'
                = uu.text_field :url, class: 'title-form form', placeholder: "URL"
              = f.add_nested_fields_link :urls, 'ADD', class: 'btn btn-primary', role: 'button'
            - if logged_in?
              = f.submit 'Save', class: 'btn btn-white form-btn btn-size'

app/views/bookshelves/index.html.slim
  .bookmark-index-wrapper
    .col-md-12
      h1.text-center.text-white
        | Bookshelf
      .container
        .row
          .col-sm-12
            - @bookshelves.each do |bookshelf|
              .bookmark-index-single.mt-5
                p.bookmark-text
                  = bookshelf.url
                = form_for @url do |f|
                  = f.select :bookmark_id, options_for_select(@bookmarks.map{|bm| ["#{bm.title}", bm.id]}, {class: 'form-control'}),:prompt => 'SELECT TITLE'
                  = f.hidden_field :url, :value => bookshelf.url
                  = f.hidden_field :bookshelf_id, :value => bookshelf.id
                  = f.submit "ADD", class: 'btn btn-primary', role: 'button'
              

app/views/links/index.html.slim
  .bookmark-index-wrapper
    .col-md-12
      h1.text-center.text-white
        | Link
      .container
        .row
          .col-sm-12.text-center.mt-3
            = image_tag "Passing-book_QR_Code.png"
      .container
        .row
          .col-sm-12
            .clip.text-left.mt-5
              textarea.text-right#bar rows="1" wrap="off" style="overflow: overlay;"
                | javascript: (function () { var b = location.href, a = new XMLHttpRequest; a.open("POST", "https://passing-book.herokuapp.com/bookshelves/save"); a.onreadystatechange = function () { 4 == a.readyState && (204 != a.status ? alert("\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u4e0b\u3055\u3044\u3002") : alert("\u4fdd\u5b58\u306b\u6210\u529f\u3057\u307e\u3057\u305f\u3002")) }; a.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); a.send("data=" + b + "&user_id=#{current_user.id}") })();
              br
              button.btn.btn-secondary.clipboard-btn data-clipboard-action="copy" data-clipboard-target="#bar"
                | COPY
            h4 登録方法
            ol
              li "COPY"を押してクリップボードへコピーする
              li 何でも良いので、ブラウザでブックマークの登録を行う
              li 登録したブックマークの編集画面を開く
              li "URL"の項目に"1."でコピーしたものを貼り付ける
              li タイトルを分かりやすいものに変更する　例:ブックマークツール
              li 保存をする
              li お好きなページでブックマークを開き登録したブックマークを押す
              li アプリ内の"Bookshelf"を選択
              li 開いていたページが保存されます
              li アプリ何のブックマークに登録できます
            / h4 スマートフォン登録
    




                  

app/views/urls/new.html.slim
h1 Urls#new
p Find me in app/views/urls/new.html.slim

app/views/users/new.html.slim
.users-new-wrapper
  .container
    .row
      .col-md-offset-4.col-md-4.users-new-container
      .col-md-offset-4.col-md-4
        h1.text-center.text-white
          | Sign up
        = form_for @user do |f|
          .form-group
            = f.label :name, class: 'text-white form-text'
            = f.text_field :name, class: 'form-control' , placeholder: "Username"
          .form-group
            = f.label :email, class: 'text-white form-text'
            = f.text_field :email, class: 'form-control' , placeholder: "Email"
          .form-group
            = f.label :password, class: 'text-white form-text'
            = f.password_field :password, class: 'form-control' , placeholder: "Password"
          .form-group
            = f.label :password_confirmation, class: 'text-white form-text'
            = f.password_field :password_confirmation, class: 'form-control' , placeholder: "Password"
          = f.submit "Sign", class: 'btn btn-block btn-white'
          / = link_to 'Login', login_path,class: 'text-login'

        / .card-body
        /   .input-group.no-border.input-lg
        /     .input-group-prepend
        /       span.input-group-text
        /         i.now-ui-icons.users_circle-08
        /     input.form-control placeholder=("First Name...") type="text" /
        /   .input-group.no-border.input-lg
        /     .input-group-prepend
        /       span.input-group-text
        /         i.now-ui-icons.text_caps-small
        /     input.form-control placeholder=("Last Name...") type="text" /
        /   .card-footer.text-center
        /     a.btn.btn-primary.btn-round.btn-lg.btn-block href="#pablo"  Get Started