config/routes.rb
Rails.application.routes.draw do
  # get 'bookshelves/new'
  # get 'bookmarks/new'
  # post 'bookmarks/new'
  # post 'bookmarks/save', to:  'bookmarks#save'
  # get  'bookshelf/new'
  post 'bookshelves/save', to:  'bookshelves#save'
  # get 'urls/new'
  # get 'urls/show'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :bookmarks
  resources :urls
  resources :bookshelves
  resources :links
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  # validates :url, presence: true
  validates :title, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :books
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :user_id, presence: true
  # validates :description, presence: true
  # validates :title, presence: true
  # validates :image, presence: true

  belongs_to :user
  has_many :urls, dependent: :destroy
  accepts_nested_attributes_for :urls,  allow_destroy: true
  has_many :bookshelves
end

app/models/bookshelf.rb
class Bookshelf < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_many :bookmarks
  acts_as_paranoid
  # accepts_nested_attributes_for :urls,  allow_destroy: true

end

app/models/url.rb
class Url < ApplicationRecord
  validates :url, presence: true
  # belongs_to :user
  belongs_to :bookmark
  has_many :bookshelves
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
  # パスワードの文字数を8~32文字のみ可能にしてください
  validates :password,
            length: { minimum: 8, maximum: 32 }
  # アルファベットだけ、数字だけのパスワードは不可とします。
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/i }

  # 最低限「~ @ ~ . ~」の形を許可するようにしてください。
  validates :email,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # 15文字まで許可するようにバリデーションを設定してください。
  validates :name,
            length: { maximum: 15 }

  has_many :bookmarks
  has_many :urls
  has_many :bookshelves
  accepts_nested_attributes_for :urls, allow_destroy: true
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :logged_in_user, only: [:post, :index, :edit, :update, :destroy]
  def index
    # ログインしているユーザーのみの情報を取得
    @bookmarks = current_user.bookmarks
  end

  def new
    @bookmark = Bookmark.new
    @bookmark.urls.build
  end

  def save
    @bookmark = Bookmark.new
    @bookmark.urls.build
    @bookmark = current_user.bookmarks.new(bookmark_params)
    @bookmark.save
  end

  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmarks_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update_attributes(bookmark_params)
      redirect_to bookmarks_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :edit
    end    
  end

  def destroy
    @bookmark = Bookmark.find_by(id: params[:id])
    @bookmark.destroy if @bookmark.present?
    redirect_to bookmarks_path, warning: 'Delete'
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:description, :title, urls_attributes: [:url, :_destroy,:id])
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to bookmarks_path, success: 'Success'
      
    else
      flash.now[:danger] = 'Failure'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'Log out'
  end

  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
    @url.book_id = params[:bookmark_id]
    @url_user_id = session[:user_id]
  end

  def create
    @url = Url.new(url_params)
    if url_params[:bookmark_id].empty?
      flash[:danger] = "Please select bookmark."
      redirect_to bookshelves_path
    end
    if @url.save
      # bookshelf_params(ハッシュ)から:bookshelf_id(キー)を指定して、bookshelf_idのvalueを取り出す
      @bookshelf = Bookshelf.find(bookshelf_params[:bookshelf_id])
      @bookshelf.destroy if @bookshelf.present?
      redirect_to bookmarks_path, success: 'Add bookmark.'
    # else
    #   flash[:danger] = "ブックマークの追加に失敗しました"
    #   redirect_to bookshelves_path
    end
  end

  private
  def url_params
    params.require(:url).permit(:bookmark_id, :url)
  end

  def bookshelf_params
    params.require(:url).permit(:bookshelf_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'Success'
    else
      flash.now[:danger] = "Failure"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end

  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/bookshelves_helper.rb
module BookshelvesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Passing-book
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta content="width=device-width,initial-scale=1" name="viewport"
  body
    - flash.each do |key, value|
      div class=("alert alert-#{key}") role="alert" = value
    nav.navbar.navbar-expand-xl.fixed-top.navbar-light.bg-light.shadow color-on-scroll="400" 
        button.navbar-toggler.navbar-toggler-right.collapsed[type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
        = link_to root_path do
          span
          = image_tag "icons/emblemmatic-p-b-logo-148.png", class: "navbar-brand "
        #navbarToggler.navbar-collapse.collapse[style=""]
          ul.navbar-nav.mt-2.mt-md-0.ml-auto
            -if logged_in?
              li.nav-item
                =link_to 'Home',root_path , class: "nav-link"
              li.nav-item
                =link_to 'Save',new_bookmark_path , class: "nav-link"
              li.nav-item
                =link_to 'Bookshelf',bookshelves_path , class: "nav-link"
              li.nav-item
                =link_to 'Bookmark',bookmarks_path , class: "nav-link"
              li.nav-item
                =link_to 'Link',links_path , class: "nav-link"
              li.nva-item
                =link_to 'Log Out',logout_path, class: "nav-link", method: :delete 
            -else
              li.nav-item
                =link_to 'Home',root_path , class: "nav-link"
              li.nva-item
                =link_to 'Sign up',new_user_path , class: "nav-link"
              li.nva-item
                =link_to 'Log In',login_path , class: "nav-link"
                / =link_to 'Log Out',logout_path, class: "nav-link", method: :delete 
    = yield
    script
        |  $(function () { $(".alert").fadeOut(2000); }); 
  / footer.navbar.navbar-expand-xl.fixed-bottom.navbar-transparent
  /   small
  /     | (C)2019 pict-studio. 

app/views/pages/help.html.slim
h1
  | ヘルプページです

app/views/pages/index.html.slim
.top-jumbotron-wrapper.text-center
  .container.top-jumbotron-container
    h1.text-white
      | Welcome
    h2.text-white
    .row
      .col-md-offset-3.col-md-3.users-new-container
      .col-md-offset-3.col-md-3
        = link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white '
      .col-md-3
        = link_to 'Log in', login_path,class: 'btn btn-block btn-white'
          